# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '12x20x20demo_analyze_main_2.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1071, 904)
        Dialog.setStyleSheet("background-color: rgb(99, 99, 99);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(-510, -60, 1600, 191))
        # changed geometry due to lacking right-side length
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setLineWidth(0)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_alpha = QtWidgets.QPushButton(Dialog)
        self.pushButton_alpha.setGeometry(QtCore.QRect(10, 140, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(20)
        self.pushButton_alpha.setFont(font)
        self.pushButton_alpha.setStyleSheet(
            "background-color: rgb(0, 0, 0);\n" "color: rgb(255, 255, 255);"
        )
        self.pushButton_alpha.setObjectName("pushButton_alpha")
        self.pushButton_beta = QtWidgets.QPushButton(Dialog)
        self.pushButton_beta.setGeometry(QtCore.QRect(160, 140, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(20)
        self.pushButton_beta.setFont(font)
        self.pushButton_beta.setStyleSheet(
            "background-color: rgb(0, 0, 0);\n" "color: rgb(255, 255, 255);"
        )
        self.pushButton_beta.setObjectName("pushButton_beta")
        self.pushButton_zeta = QtWidgets.QPushButton(Dialog)
        self.pushButton_zeta.setGeometry(QtCore.QRect(760, 140, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(20)
        self.pushButton_zeta.setFont(font)
        self.pushButton_zeta.setStyleSheet(
            "background-color: rgb(0, 0, 0);\n" "color: rgb(255, 255, 255);"
        )
        self.pushButton_zeta.setObjectName("pushButton_zeta")
        self.pushButton_beta_transport = QtWidgets.QPushButton(Dialog)
        self.pushButton_beta_transport.setGeometry(
            QtCore.QRect(160, 190, 141, 31)
        )
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(9)
        self.pushButton_beta_transport.setFont(font)
        self.pushButton_beta_transport.setStyleSheet(
            "background-color: rgb(0, 0, 0);\n" "color: rgb(255, 255, 255);"
        )
        self.pushButton_beta_transport.setObjectName(
            "pushButton_beta_transport"
        )
        self.pushButton_alpha_transport = QtWidgets.QPushButton(Dialog)
        self.pushButton_alpha_transport.setGeometry(
            QtCore.QRect(10, 190, 141, 31)
        )
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(9)
        self.pushButton_alpha_transport.setFont(font)
        self.pushButton_alpha_transport.setStyleSheet(
            "background-color: rgb(0, 0, 0);\n" "color: rgb(255, 255, 255);"
        )
        self.pushButton_alpha_transport.setObjectName(
            "pushButton_alpha_transport"
        )
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(780, 270, 281, 641))
        self.groupBox.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setAcceptDrops(False)
        self.groupBox.setStyleSheet("border-radius: 15px")
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_countbox = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_countbox.setGeometry(QtCore.QRect(50, 130, 211, 381))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(16)
        self.pushButton_countbox.setFont(font)
        self.pushButton_countbox.setStyleSheet(
            "background-color: rgb(238, 238, 238);"
        )
        self.pushButton_countbox.setObjectName("pushButton_countbox")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(70, 40, 171, 561))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_41 = QtWidgets.QLabel(self.groupBox)
        self.label_41.setGeometry(QtCore.QRect(60, 80, 191, 481))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.label_hide_3 = QtWidgets.QLabel(self.groupBox)
        self.label_hide_3.setGeometry(QtCore.QRect(-100, 480, 1161, 701))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_hide_3.setFont(font)
        self.label_hide_3.setStyleSheet(
            "background-color: rgb(255, 255, 255);"
        )
        self.label_hide_3.setText("")
        self.label_hide_3.setObjectName("label_hide_3")
        self.label_41.raise_()
        self.label_11.raise_()
        self.pushButton_countbox.raise_()
        self.label_hide_3.raise_()
        self.pushButton_total = QtWidgets.QPushButton(Dialog)
        self.pushButton_total.setGeometry(QtCore.QRect(940, 140, 101, 81))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(12)
        self.pushButton_total.setFont(font)
        self.pushButton_total.setStyleSheet(
            "background-color: rgb(0, 0, 0);\n" "color: rgb(255, 255, 255);"
        )
        self.pushButton_total.setObjectName("pushButton_total")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(-10, 390, 631, 631))
        self.groupBox_2.setStyleSheet("border-radius: 15px")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(-30, 280, 661, 16))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.lcd_boxes_in_use = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcd_boxes_in_use.setGeometry(QtCore.QRect(420, 200, 231, 71))
        self.lcd_boxes_in_use.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcd_boxes_in_use.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_boxes_in_use.setProperty("value", 0.0)
        self.lcd_boxes_in_use.setObjectName("lcd_boxes_in_use")
        self.lcd_boxes_free = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcd_boxes_free.setGeometry(QtCore.QRect(420, 310, 231, 71))
        self.lcd_boxes_free.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcd_boxes_free.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_boxes_free.setProperty("value", 0.0)
        self.lcd_boxes_free.setObjectName("lcd_boxes_free")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(50, 320, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.lcd_totalsamples = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcd_totalsamples.setGeometry(QtCore.QRect(420, 90, 231, 71))
        self.lcd_totalsamples.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcd_totalsamples.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_totalsamples.setProperty("value", 0.0)
        self.lcd_totalsamples.setObjectName("lcd_totalsamples")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(30, 460, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(-60, 390, 691, 16))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "border-radius: 15px"
        )
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(0, 170, 631, 16))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(-160, 60, 791, 16))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(50, 430, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.lcd_average_fill = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcd_average_fill.setGeometry(QtCore.QRect(420, 420, 231, 71))
        self.lcd_average_fill.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcd_average_fill.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_average_fill.setProperty("value", 0.0)
        self.lcd_average_fill.setObjectName("lcd_average_fill")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(50, 210, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(50, 0, 571, 41))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.label_42 = QtWidgets.QLabel(self.groupBox_2)
        self.label_42.setGeometry(QtCore.QRect(-10, 70, 631, 20))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.groupBox_2)
        self.label_43.setGeometry(QtCore.QRect(-10, 180, 631, 20))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.groupBox_2)
        self.label_44.setGeometry(QtCore.QRect(-10, 290, 631, 20))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.label_44.setText("")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.groupBox_2)
        self.label_45.setGeometry(QtCore.QRect(-10, 400, 631, 20))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.label_45.setText("")
        self.label_45.setObjectName("label_45")
        self.label_45.raise_()
        self.label_44.raise_()
        self.label_43.raise_()
        self.label_42.raise_()
        self.label_6.raise_()
        self.lcd_boxes_in_use.raise_()
        self.lcd_boxes_free.raise_()
        self.label_7.raise_()
        self.lcd_totalsamples.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_8.raise_()
        self.lcd_average_fill.raise_()
        self.label_3.raise_()
        self.label_15.raise_()
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(680, 360, 20, 601))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.informatic_title = QtWidgets.QLabel(Dialog)
        self.informatic_title.setGeometry(QtCore.QRect(40, 310, 631, 91))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(48)
        self.informatic_title.setFont(font)
        self.informatic_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.informatic_title.setObjectName("informatic_title")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(30, 80, 941, 41))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_17.setFrameShape(QtWidgets.QFrame.Box)
        self.label_17.setLineWidth(0)
        self.label_17.setAlignment(
            QtCore.Qt.AlignLeading
            | QtCore.Qt.AlignLeft
            | QtCore.Qt.AlignVCenter
        )
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(320, 80, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setLineWidth(0)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(30, 70, 551, 6))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "background-color: rgb(0, 0, 0);"
        )
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.pushButton_about = QtWidgets.QPushButton(Dialog)
        self.pushButton_about.setGeometry(QtCore.QRect(790, 0, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(12)
        self.pushButton_about.setFont(font)
        self.pushButton_about.setStyleSheet(
            "background-color: rgb(0, 0, 0);\n" "color: rgb(255, 255, 255);"
        )
        self.pushButton_about.setObjectName("pushButton_about")
        self.lcd_active = QtWidgets.QLCDNumber(Dialog)
        self.lcd_active.setGeometry(QtCore.QRect(230, 80, 111, 41))
        self.lcd_active.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lcd_active.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_active.setProperty("value", 0.0)
        self.lcd_active.setObjectName("lcd_active")
        self.lcd_disposed = QtWidgets.QLCDNumber(Dialog)
        self.lcd_disposed.setGeometry(QtCore.QRect(480, 80, 111, 41))
        self.lcd_disposed.setStyleSheet(
            "background-color: rgb(255, 255, 255);"
        )
        self.lcd_disposed.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_disposed.setProperty("value", 0.0)
        self.lcd_disposed.setObjectName("lcd_disposed")
        self.pushButton_gamma = QtWidgets.QPushButton(Dialog)
        self.pushButton_gamma.setGeometry(QtCore.QRect(440, 140, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(20)
        self.pushButton_gamma.setFont(font)
        self.pushButton_gamma.setStyleSheet(
            "background-color: rgb(0, 0, 0);\n" "color: rgb(255, 255, 255);"
        )
        self.pushButton_gamma.setObjectName("pushButton_gamma")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(650, 400, 20, 561))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(710, 320, 20, 691))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(740, 280, 20, 691))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(770, 240, 20, 701))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(10, 230, 1061, 4))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(10, 240, 751, 4))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(10, 280, 721, 4))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(10, 250, 751, 4))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(10, 260, 751, 4))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setGeometry(QtCore.QRect(10, 270, 751, 4))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(Dialog)
        self.label_28.setGeometry(QtCore.QRect(10, 290, 721, 4))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(Dialog)
        self.label_29.setGeometry(QtCore.QRect(10, 300, 721, 4))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(Dialog)
        self.label_30.setGeometry(QtCore.QRect(10, 310, 721, 4))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(830, 250, 571, 41))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(18)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.pushButton_epsilon = QtWidgets.QPushButton(Dialog)
        self.pushButton_epsilon.setGeometry(QtCore.QRect(600, 140, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(20)
        self.pushButton_epsilon.setFont(font)
        self.pushButton_epsilon.setStyleSheet(
            "background-color: rgb(0, 0, 0);\n" "color: rgb(255, 255, 255);"
        )
        self.pushButton_epsilon.setObjectName("pushButton_epsilon")
        self.label_31 = QtWidgets.QLabel(Dialog)
        self.label_31.setGeometry(QtCore.QRect(915, 140, 21, 81))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(Dialog)
        self.label_32.setGeometry(QtCore.QRect(30, 150, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(Dialog)
        self.label_33.setGeometry(QtCore.QRect(180, 160, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(Dialog)
        self.label_34.setGeometry(QtCore.QRect(200, 160, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("background-color: rgb(50,50,50)")
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(Dialog)
        self.label_35.setGeometry(QtCore.QRect(50, 160, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("background-color: rgb(50,50,50)")
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(Dialog)
        self.label_36.setGeometry(QtCore.QRect(220, 160, 21, 51))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(Dialog)
        self.label_37.setGeometry(QtCore.QRect(70, 160, 21, 51))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.pushButton_about_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_about_2.setGeometry(QtCore.QRect(790, 80, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(12)
        self.pushButton_about_2.setFont(font)
        self.pushButton_about_2.setStyleSheet(
            "background-color: rgb(126, 126, 126);\n"
            "color: rgb(255, 255, 255);"
        )
        self.pushButton_about_2.setObjectName("pushButton_about_2")
        self.label_40 = QtWidgets.QLabel(Dialog)
        self.label_40.setGeometry(QtCore.QRect(310, 140, 121, 81))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.label_46 = QtWidgets.QLabel(Dialog)
        self.label_46.setGeometry(QtCore.QRect(660, 440, 21, 511))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.label_46.setText("")
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(Dialog)
        self.label_47.setGeometry(QtCore.QRect(690, 400, 21, 511))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.label_47.setText("")
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(Dialog)
        self.label_48.setGeometry(QtCore.QRect(730, 360, 21, 561))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(Dialog)
        self.label_49.setGeometry(QtCore.QRect(760, 320, 21, 601))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(Dialog)
        self.label_50.setGeometry(QtCore.QRect(800, 240, 21, 691))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.label_50.setText("")
        self.label_50.setObjectName("label_50")
        self.label_hide_1 = QtWidgets.QLabel(Dialog)
        self.label_hide_1.setGeometry(QtCore.QRect(-30, -30, 1161, 981))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(28)
        self.label_hide_1.setFont(font)
        self.label_hide_1.setStyleSheet(
            "background-color: rgb(255, 255, 255);"
        )
        self.label_hide_1.setText("")
        self.label_hide_1.setObjectName("label_hide_1")
        self.label_hide_8 = QtWidgets.QLabel(Dialog)
        self.label_hide_8.setGeometry(QtCore.QRect(-50, 560, 341, 20))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(48)
        self.label_hide_8.setFont(font)
        self.label_hide_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_hide_8.setStyleSheet("background-color: rgb(50,50,50)")
        self.label_hide_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_hide_8.setLineWidth(0)
        self.label_hide_8.setText("")
        self.label_hide_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hide_8.setObjectName("label_hide_8")
        self.label_hide_9 = QtWidgets.QLabel(Dialog)
        self.label_hide_9.setGeometry(QtCore.QRect(-40, 520, 1161, 20))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(48)
        self.label_hide_9.setFont(font)
        self.label_hide_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_hide_9.setStyleSheet("background-color: rgb(50,50,50)")
        self.label_hide_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_hide_9.setLineWidth(0)
        self.label_hide_9.setText("")
        self.label_hide_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hide_9.setObjectName("label_hide_9")
        self.label_hide_4 = QtWidgets.QLabel(Dialog)
        self.label_hide_4.setGeometry(QtCore.QRect(-290, 50, 1651, 191))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(72)
        self.label_hide_4.setFont(font)
        self.label_hide_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_hide_4.setStyleSheet(
            "background-color: rgb(255, 255, 255);"
        )
        self.label_hide_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_hide_4.setLineWidth(0)
        self.label_hide_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hide_4.setObjectName("label_hide_4")
        self.label_hide_7 = QtWidgets.QLabel(Dialog)
        self.label_hide_7.setGeometry(QtCore.QRect(310, 560, 561, 20))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(48)
        self.label_hide_7.setFont(font)
        self.label_hide_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_hide_7.setStyleSheet("background-color: rgb(50,50,50)")
        self.label_hide_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_hide_7.setLineWidth(0)
        self.label_hide_7.setText("")
        self.label_hide_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hide_7.setObjectName("label_hide_7")
        self.label_hide_6 = QtWidgets.QLabel(Dialog)
        self.label_hide_6.setGeometry(QtCore.QRect(890, 560, 831, 20))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(48)
        self.label_hide_6.setFont(font)
        self.label_hide_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_hide_6.setStyleSheet("background-color: rgb(50,50,50)")
        self.label_hide_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_hide_6.setLineWidth(0)
        self.label_hide_6.setText("")
        self.label_hide_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hide_6.setObjectName("label_hide_6")
        self.pushButton_begin = QtWidgets.QPushButton(Dialog)
        self.pushButton_begin.setGeometry(QtCore.QRect(-110, 340, 1291, 91))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(18)
        self.pushButton_begin.setFont(font)
        self.pushButton_begin.setStyleSheet(
            "background-color: rgb(0, 0, 0);\n" "color: rgb(255, 255, 255);"
        )
        self.pushButton_begin.setObjectName("pushButton_begin")
        self.label_hide_5 = QtWidgets.QLabel(Dialog)
        self.label_hide_5.setGeometry(QtCore.QRect(-290, 600, 1651, 321))
        font = QtGui.QFont()
        font.setFamily("Android 101")
        font.setPointSize(48)
        self.label_hide_5.setFont(font)
        self.label_hide_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_hide_5.setStyleSheet(
            "color: rgb(255, 255, 255);\n"
            "background-color: rgb(50,50,50)\n"
            ""
        )
        self.label_hide_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_hide_5.setLineWidth(0)
        self.label_hide_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hide_5.setObjectName("label_hide_5")
        self.label_49.raise_()
        self.label_48.raise_()
        self.label_47.raise_()
        self.label_46.raise_()
        self.label_40.raise_()
        self.label_33.raise_()
        self.label_32.raise_()
        self.label_22.raise_()
        self.label.raise_()
        self.pushButton_zeta.raise_()
        self.groupBox.raise_()
        self.pushButton_total.raise_()
        self.groupBox_2.raise_()
        self.label_12.raise_()
        self.informatic_title.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_13.raise_()
        self.pushButton_about.raise_()
        self.lcd_active.raise_()
        self.lcd_disposed.raise_()
        self.pushButton_gamma.raise_()
        self.label_16.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_23.raise_()
        self.label_25.raise_()
        self.label_24.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.label_14.raise_()
        self.pushButton_epsilon.raise_()
        self.label_31.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.pushButton_alpha.raise_()
        self.pushButton_alpha_transport.raise_()
        self.pushButton_beta_transport.raise_()
        self.pushButton_beta.raise_()
        self.pushButton_about_2.raise_()
        self.label_50.raise_()
        self.label_hide_1.raise_()
        self.label_hide_8.raise_()
        self.label_hide_9.raise_()
        self.label_hide_4.raise_()
        self.label_hide_7.raise_()
        self.label_hide_6.raise_()
        self.pushButton_begin.raise_()
        self.label_hide_5.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "BIN ANALYTICS (DEMO)"))
        self.label.setText(_translate("Dialog", "BIN ANALYTICS"))
        self.pushButton_alpha.setText(_translate("Dialog", "ALPHA"))
        self.pushButton_beta.setText(_translate("Dialog", "BETA"))
        self.pushButton_zeta.setText(_translate("Dialog", "ZETA"))
        self.pushButton_beta_transport.setText(
            _translate("Dialog", "TRANSPORT")
        )
        self.pushButton_alpha_transport.setText(
            _translate("Dialog", "TRANSPORT")
        )
        self.pushButton_countbox.setText(
            _translate("Dialog", "ENGAGE\n" "VISUALIZATION")
        )
        self.pushButton_total.setText(_translate("Dialog", "TOTAL"))
        self.label_7.setText(_translate("Dialog", "BINS INACTIVE:"))
        self.label_9.setText(_translate("Dialog", " PER BIN:"))
        self.label_2.setText(_translate("Dialog", "TOTAL SAMPLES:"))
        self.label_8.setText(_translate("Dialog", "AVERAGE FILL"))
        self.label_3.setText(_translate("Dialog", "BINS ACTIVE:"))
        self.label_15.setText(_translate("Dialog", "INFORMATICS AT A GLANCE"))
        self.informatic_title.setText(_translate("Dialog", "SAMPLE"))
        self.label_17.setText(_translate("Dialog", "ACTIVE SAMPLES:"))
        self.label_18.setText(_translate("Dialog", "DISPOSED:"))
        self.pushButton_about.setText(
            _translate(
                "Dialog",
                "ABOUT THIS PROGRAM\n" "//////////\n" "V 1.0.0 DEMO EDITION",
            )
        )
        self.pushButton_gamma.setText(_translate("Dialog", "GAMMA"))
        self.label_14.setText(_translate("Dialog", "VISUALIZE DATA"))
        self.pushButton_epsilon.setText(_translate("Dialog", "EPSILON"))
        self.pushButton_about_2.setText(_translate("Dialog", "TUTORIAL "))
        self.label_hide_4.setText(_translate("Dialog", "BIN ANALYTICS"))
        self.pushButton_begin.setText(_translate("Dialog", "BEGIN ANALYSIS"))
        self.label_hide_5.setText(
            _translate("Dialog", "BENJAMIN CLEWELL\n" "\\\\\\\\\\ \n" "DEMO")
        )
